---
- include: set_facts.yml
- include: registration.yml
  when: satellite_connected == "True"
- include: firewall.yml
- include: install_software.yml
- include: install_satellite.yml
- include: configure_satellite.yml
- include: satellite_post_config.yml
